Add support for VSCode
haydar-metin/glsp-playwright pull request #1
Opened 2023-06-09 13:02 UTC by haydar-metin

This PR is part of my diploma research conducted at the [Model Engineering lab](https://me.big.tuwien.ac.at/) of TU Wien in the [Business Informatics Group](https://www.big.tuwien.ac.at/).

---

- Necessary **Page Objects** for VSCode are added
- Necessary **Integration** for VSCode is added 
- **Setup logic** for setting the environment is provided
  - Including downloading VSCode and installing extensions 

# Disclaimer:

The current GLSP-VSCode Integration does not have support for creating `vsix` files.

The following `package.json` can be used to create the `vsix` file. Afterward, run `yarn package`.

```json
{
  "name": "workflow-vscode-example",
  "displayName": "Workflow GLSP Example",
  "version": "1.1.0-next",
  "private": "true",
  "description": "An example graphical language used for modeling workflows",
  "categories": [
    "Programming Languages"
  ],
  "homepage": "https://www.eclipse.org/glsp/",
  "bugs": "https://github.com/eclipse-glsp/glsp/issues",
  "repository": {
    "type": "git",
    "url": "https://github.com/eclipse-glsp/glsp-vscode-integration.git"
  },
  "author": {
    "name": "EclipseGLSP"
  },
  "contributors": [
    {
      "name": "Eclipse GLSP Project",
      "email": "glsp-dev@eclipse.org",
      "url": "https://projects.eclipse.org/projects/ecd.glsp"
    }
  ],
  "publisher": "Eclipse-GLSP",
  "main": "./lib/workflow-extension",
  "files": [
    "lib",
    "dist"
  ],
  "scripts": {
    "build": "tsc -b",
    "clean": "rimraf lib tsconfig.tsbuildinfo ",
    "esbuild": "npm run esbuild-base --sourcemap",
    "esbuild-base": "esbuild ./src/workflow-extension.ts --bundle --outfile=lib/workflow-extension.js --external:vscode --format=cjs --platform=node",
    "lint": "eslint --ext .ts,.tsx ./src",
    "lint:ci": "yarn lint -o eslint.xml -f checkstyle",
    "package": "yarn clean && vsce package --yarn",
    "prepare": "yarn clean && yarn build",
    "vscode:prepublish": "npm run esbuild-base",
    "watch": "tsc -w"
  },
  "contributes": {
    "commands": [
      {
        "command": "workflow.fit",
        "title": "Fit to Screen",
        "category": "Workflow Diagram",
        "enablement": "activeCustomEditorId == 'workflow.glspDiagram'"
      },
      {
        "command": "workflow.center",
        "title": "Center selection",
        "category": "Workflow Diagram",
        "enablement": "activeCustomEditorId == 'workflow.glspDiagram'"
      },
      {
        "command": "workflow.layout",
        "title": "Layout diagram",
        "category": "Workflow Diagram",
        "enablement": "activeCustomEditorId == 'workflow.glspDiagram'"
      },
      {
        "command": "workflow.goToNextNode",
        "title": "Go to next Node",
        "category": "Workflow Navigation",
        "enablement": "activeCustomEditorId == 'workflow.glspDiagram' && workflow.editorSelectedElementsAmount == 1"
      },
      {
        "command": "workflow.goToPreviousNode",
        "title": "Go to previous Node",
        "category": "Workflow Navigation",
        "enablement": "activeCustomEditorId == 'workflow.glspDiagram' && workflow.editorSelectedElementsAmount == 1"
      },
      {
        "command": "workflow.showDocumentation",
        "title": "Show documentation...",
        "category": "Workflow Diagram",
        "enablement": "activeCustomEditorId == 'workflow.glspDiagram' && workflow.editorSelectedElementsAmount == 1"
      },
      {
        "command": "workflow.exportAsSVG",
        "title": "Export as SVG",
        "category": "Workflow Diagram",
        "enablement": "activeCustomEditorId == 'workflow.glspDiagram'"
      }
    ],
    "customEditors": [
      {
        "viewType": "workflow.glspDiagram",
        "displayName": "Workflow Diagram Editor",
        "selector": [
          {
            "filenamePattern": "*.wf"
          }
        ]
      }
    ],
    "keybindings": [
      {
        "key": "alt+f",
        "mac": "alt+f",
        "command": "workflow.fit",
        "when": "activeCustomEditorId == 'workflow.glspDiagram'"
      },
      {
        "key": "alt+c",
        "mac": "alt+c",
        "command": "workflow.center",
        "when": "activeCustomEditorId == 'workflow.glspDiagram'"
      },
      {
        "key": "ctrl+a",
        "mac": "ctrl+a",
        "command": "workflow.selectAll",
        "when": "activeCustomEditorId == 'workflow.glspDiagram'"
      },
      {
        "key": "alt+l",
        "mac": "alt+l",
        "command": "workflow.layout",
        "when": "activeCustomEditorId == 'workflow.glspDiagram'"
      },
      {
        "key": "alt+e",
        "mac": "alt+e",
        "command": "workflow.exportAsSVG",
        "when": "activeCustomEditorId == 'workflow.glspDiagram'"
      },
      {
        "key": "Ctrl+4",
        "mac": "cmd+4",
        "command": "workflow.goToNextNode",
        "when": "activeCustomEditorId == 'workflow.glspDiagram' && workflow.editorSelectedElementsAmount == 1"
      },
      {
        "key": "Ctrl+3",
        "mac": "cmd+3",
        "command": "workflow.goToPreviousNode",
        "when": "activeCustomEditorId == 'workflow.glspDiagram' && workflow.editorSelectedElementsAmount == 1"
      }
    ],
    "menus": {
      "editor/title": [
        {
          "submenu": "workflow.editor.title",
          "group": "bookmarks"
        },
        {
          "command": "workflow.goToNextNode",
          "group": "navigation",
          "when": "activeCustomEditorId == 'workflow.glspDiagram' && workflow.editorSelectedElementsAmount == 1"
        },
        {
          "command": "workflow.goToPreviousNode",
          "group": "navigation",
          "when": "activeCustomEditorId == 'workflow.glspDiagram' && workflow.editorSelectedElementsAmount == 1"
        },
        {
          "command": "workflow.showDocumentation",
          "group": "navigation",
          "when": "activeCustomEditorId == 'workflow.glspDiagram' && workflow.editorSelectedElementsAmount == 1"
        }
      ],
      "workflow.editor.title": [
        {
          "command": "workflow.fit",
          "group": "navigation",
          "when": "activeCustomEditorId == 'workflow.glspDiagram'"
        },
        {
          "command": "workflow.center",
          "group": "navigation",
          "when": "activeCustomEditorId == 'workflow.glspDiagram'"
        },
        {
          "command": "workflow.layout",
          "group": "navigation",
          "when": "activeCustomEditorId == 'workflow.glspDiagram'"
        },
        {
          "command": "workflow.exportAsSVG",
          "when": "activeCustomEditorId == 'workflow.glspDiagram'"
        }
      ]
    },
    "submenus": [
      {
        "id": "workflow.editor.title",
        "label": "Diagram"
      }
    ]
  },
  "activationEvents": [
    "*"
  ],
  "devDependencies": {
    "@eclipse-glsp-examples/workflow-server": "next",
    "@eclipse-glsp/vscode-integration": "1.1.0-next",
    "@vscode/vsce": "^2.19.0",
    "esbuild": "^0.17.19"
  },
  "engines": {
    "vscode": "^1.54.0"
  }
}
```

2023-06-30 13:17 UTC, martin-fleck-at requested changes
HI @haydar-metin,

I already had a look at this PR and most of the things look good to me, so great work as usual! However, I'm not the biggest fan of the VS Code properties bleeding into the general setup (and not being simply part of the integration options).

Also, for me the test cases do not run through as two tests keep failing:

```
  1) [all] › ../../tests/features/tool-palette.spec.ts:40:9 › The tool palette › should allow to access the content items 

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "Nodes"
    Received: "NODES"

      43 |         const groups = await toolPalette.content.toolGroups();
      44 |         expect(groups.length).toBe(2);
    > 45 |         expect(await groups[0].header()).toBe('Nodes');
         |                                          ^
      46 |         expect(await groups[1].header()).toBe('Edges');
      47 |
      48 |         const elements0 = await groups[0].items();

        at /home/martin/Git/OpenSource/eclipse-glsp/glsp-playwright/examples/workflow-test/tests/features/tool-palette.spec.ts:45:42

  2) [all] › ../../tests/features/tool-palette.spec.ts:71:9 › The tool palette › should allow to access the toolbar items 

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "Nodes"
    Received: "NODES"

       96 |         const groups = await toolPalette.content.toolGroups();
       97 |         expect(groups.length).toBe(1);
    >  98 |         expect(await groups[0].header()).toBe('Nodes');
          |                                          ^
       99 |
      100 |         const elements0 = await groups[0].items();
      101 |         expect(elements0.length).toBe(1);

        at /home/martin/Git/OpenSource/eclipse-glsp/glsp-playwright/examples/workflow-test/tests/features/tool-palette.spec.ts:98:42

  2 failed
    [all] › ../../tests/features/tool-palette.spec.ts:40:9 › The tool palette › should allow to access the content items 
    [all] › ../../tests/features/tool-palette.spec.ts:71:9 › The tool palette › should allow to access the toolbar items 
```

I just manually confirmed but in VS Code the toolbar titles (Nodes, Edges) are really upper case. What would be the best way to customize this for the VS Code integration? Could you please have another look at it?

2023-06-30 13:17 UTC, martin-fleck-at commented on packages/glsp-playwright/src/test.ts
> +    vscodeStoragePath?: string;
So far the options were very generic but this adds some platform-specific property. Is this necessary? Would it be possible to simply have that as part of the `integrationOptions`?

2023-06-30 13:17 UTC, martin-fleck-at commented on packages/glsp-playwright/src/test.ts
> +    vscodeStoragePath: [undefined, { option: true }],
Same here: It just feels odd that something platform-specific is in the generic test extension. I know later on we do some platform-specific creation depending on the integration options type but if there is any way we could only do that for the 'VSCode' part, I think it would be a bit nicer.

2023-07-07 15:00 UTC, haydar-metin commented
@martin-fleck-at thanks for the feedback! I moved the variables to the correct place now.

Concerning the two failing tests: We can either ignore the casing or use something like https://playwright.dev/docs/test-parameterize, what do you prefer?

2023-07-10 13:18 UTC, martin-fleck-at commented
@haydar-metin Ideally the servers would be aligned but maybe this is a good example to show off the additional capabilities of playwright with the parametrization. So I think I'd rather prefer that for now.

2023-07-16 18:35 UTC, closed without merging